apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eks
  labels:
    app: hello-eks
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-eks
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-eks
    spec:
      containers:
      - image: public.ecr.aws/t5t3s6c1/hello:latest
        imagePullPolicy: Always
        name: hello-eks
        ports:
        - containerPort: 8080
          protocol: TCP
