apiVersion: v1
kind: Service
metadata:
  name: hello-eks
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-eks
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
